[package]
name = "program_a-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = {version = "0.15", package = "libafl_libfuzzer"}
arbitrary = { version = "1.4.2", features = ["derive"] } 

[dependencies.program_a]
path = ".."

[[bin]]
name = "fuzz_target_parse_csv_ints"
path = "fuzz_targets/fuzz_target_parse_csv_ints.rs"
test = false
doc = false
bench = false
[[bin]]
name = "fuzz_target_evaluate_expression"
path = "fuzz_targets/fuzz_target_evaluate_expression.rs"
test = false
doc = false
bench = false
[[bin]]
name = "fuzz_target_extract_first_number"
path = "fuzz_targets/fuzz_target_extract_first_number.rs"
test = false
doc = false
bench = false
[[bin]]
name = "fuzz_target_parse_hex"
path = "fuzz_targets/fuzz_target_parse_hex.rs"
test = false
doc = false
bench = false
[[bin]]
name = "fuzz_target_parse_bool_or_int"
path = "fuzz_targets/fuzz_target_parse_bool_or_int.rs"
test = false
doc = false
bench = false
[[bin]]
name = "fuzz_target_add"
path = "fuzz_targets/fuzz_target_add.rs"
test = false
doc = false
bench = false