const L=acquireVsCodeApi();let g=null;function C(t={}){g=t.onRustAnalysisDone||(()=>{}),onGlobalContext=t.onGlobalContext||(()=>{}),onFuzzTargetsListed=t.onFuzzTargetsListed||(()=>{}),window.addEventListener("message",n=>{const o=n.data;switch(o.command){case"globalContext":onGlobalContext&&onGlobalContext(o.context||{});break;case"rustAnalysisDone":s("Rust analysis completed successfully"),g&&g(o.results||[]);break;case"fuzzTargetsListed":onFuzzTargetsListed&&onFuzzTargetsListed(o.targets||[]);break;default:console.warn("Unhandled message from extension:",o);break}}),a({command:"getGlobaclContext"})}function a(t){L.postMessage(t)}function s(t){a({command:"log",message:t})}let c=null,z=null,b=null;const m=document.getElementById("entry-list"),y=document.getElementById("path-display-container");function p(t,n){var o;n.innerHTML="",t=t.sort((e,i)=>i.priorityScore-e.priorityScore);for(const e of t){s(`status: ${e.status}`);const v=`<span class="status-badge" style="background:${{New:"gray",Ignore:"darkred",HarnessGenerated:"green"}[e.status]||"black"};">${e.status}</span>`,r=document.createElement("button");r.textContent="Ignore";const d=document.createElement("button");d.textContent="Generate Harness";const l=document.createElement("div");l.className="function-button",l.innerHTML=`
        <div style="font-weight:bold; margin-bottom:4px;">
      ${e.functionModulePath}::${e.functionName} ${v}
        </div>
        <div>${(o=e.functionLocation)==null?void 0:o.filePath.replace(c,"")}</div>
        <div>Priority Score: ${e.priorityScore.toFixed(3)}</div>
        <div class="btns-div" style="margin-top:6px;"></div>
      `;const f=l.getElementsByClassName("btns-div")[0];f.appendChild(r),f.appendChild(d),r.onclick=u=>{u.stopPropagation(),e.status="Ignore",s(`ignore, ${e.status}`),p(t,n)},d.onclick=u=>{u.stopPropagation(),s("generate"),e.status="HarnessGenerated"},l.onclick=()=>{a({command:"openLocation",filePath:e.functionLocation.filePath,offset:e.functionLocation.offset})},n.appendChild(l)}}function h(t){const n=t.nextElementSibling;t.classList.toggle("expanded")?n.style.display="block":n.style.display="none"}const E=document.querySelectorAll(".collapsible-header");E.forEach(t=>{s("Setting up collapsible header:",t.textContent),t.addEventListener("click",()=>{s("Collapsible header clicked:",t.textContent),h(t)})});C({onFuzzTargetsListed:t=>{s("🧪 Fuzz targets listed:");const n=document.getElementById("harness-list");if(n.innerHTML="",t.length===0){n.innerHTML="<div>No fuzz targets found.</div>";return}for(const o of t){const e=document.createElement("div");e.className="function-button",e.innerHTML=`
        <div style="font-weight:bold; margin-bottom:4px;">
          ${o.name}
        </div>
        <div>
          ${o.path.replace(z,"")}
        </div>
      `,e.onclick=()=>{a({command:"openLocation",filePath:o.path,offset:0})},n.appendChild(e)}},onRustAnalysisDone:t=>{s("Rendering function results"),m.innerHTML="",p(t,m)},onGlobalContext:t=>{s("Global context received:",t.projectRoot);const n=t.projectRoot;n?(s("📦 Got Cargo project root: "+n),c=n,y.innerHTML=`Cargo Project Root: ${n}`):y.innerHTML="No Cargo project found.";const o=document.getElementById("fuzz-path-display"),e=t.fuzzRoot;if(e)s("🧪 Got Fuzz root: "+e),z=e,o.innerHTML=`Fuzz Root: ${e}`,s("Getting Fuzz targets: "),a({command:"getFuzzTargets",fuzzRoot:e});else{o.innerText="No Fuzz root found.";const i=document.createElement("button");i.textContent="Create a Root",i.addEventListener("click",()=>{a({command:"createFuzzRoot",target:c})}),o.appendChild(i)}t.results&&t.results.length>0&&(b=t.results,p(b,m))}});document.getElementById("start-analyzer").addEventListener("click",()=>{a({command:"runAnalyzer",target:"none",projectPath:c})});document.getElementById("test-vis").addEventListener("click",()=>{a({command:"testVisualization"})});
