const S=acquireVsCodeApi();let v=null;function F(t={}){v=t.onRustAnalysisDone||(()=>{}),onGlobalContext=t.onGlobalContext||(()=>{}),onFuzzTargetsListed=t.onFuzzTargetsListed||(()=>{}),window.addEventListener("message",o=>{const n=o.data;switch(n.command){case"globalContext":onGlobalContext&&onGlobalContext(n.context||{});break;case"rustAnalysisDone":l("Rust analysis completed successfully"),v&&v(n.results||[]);break;case"fuzzTargetsListed":onFuzzTargetsListed&&onFuzzTargetsListed(n.targets||[]);break;case"refreshHarnessList":onFuzzTargetsListed&&onFuzzTargetsListed(n.targets||[]);default:console.warn("Unhandled message from extension:",n);break}}),c({command:"getGlobaclContext"})}function c(t){S.postMessage(t)}function l(t){c({command:"log",message:t})}let y=null,C=null,z=null;const p=document.getElementById("entry-list"),k=document.getElementById("path-display-container");function m(t,o,n){var s;o.innerHTML="";const a=t.filter(e=>e.status!=="Ignore"),r=t.filter(e=>e.status==="Ignore");switch(a.sort((e,i)=>i.priorityScore-e.priorityScore),n){case"unsafe-block-filter":a.sort((e,i)=>i.unsafeScore-e.unsafeScore);break;case"parameters-filter":a.sort((e,i)=>i.paramCount-e.paramCount);break;case"centrality-filter":a.sort((e,i)=>i.centralityScore-e.centralityScore);break;case"usage-filter":a.sort((e,i)=>i.usageCount-e.usageCount);break;default:a.sort((e,i)=>i.priorityScore-e.priorityScore);break}console.log("Sorted non-ignored results:",a),t=[...a,...r];for(const e of t){l(`status: ${e.status}`);const E=`<span class="status-badge" style="background:${{New:"gray",Ignore:"darkred",HarnessGenerated:"green"}[e.status]||"black"};">${e.status}</span>`,f=document.createElement("button");f.textContent="Ignore",f.className="negative-button";const u=document.createElement("button");u.textContent="Generate Harness",u.className="affirmative-button",u.style.marginLeft="4px";const d=document.createElement("div");d.className="function-button",d.innerHTML=`
      <div style="font-weight:bold; margin-bottom:4px; display: flex; gap: 2px; flex-wrap: wrap; align-items: center;">
      <span>${e.functionModulePath}::${e.functionName}</span>
    ${E}
      </div>
      <div>${(s=e.functionLocation)==null?void 0:s.filePath.replace(y,"")}</div>
      <div class="priority-score" style="margin-top: 4px;">
      Priority Score: ${e.priorityScore.toFixed(3)}
      <span 
      class="info-icon" 
      style="margin-left: 4px; cursor: pointer;" 
      title="Hover to see score breakdown">ℹ️</span>
      </div>
      <div class="btns-div" style="margin-top:6px;"></div>
      `;const b=d.getElementsByClassName("priority-score")[0];b.style.position="relative";const g=document.createElement("div");g.className="score-breakdown",g.innerHTML=`
    <strong>Score Breakdown:</strong>
    <div style="margin: 0; padding-left: 16px;">
    <div>Param Count: ${e.paramCount.toFixed(1)}</div>
    <div>Function Usage: ${e.usageCount.toFixed(1)}</div>
    <div>Centrality Score: ${e.centralityScore.toFixed(5)}</div>
    <div>Unsafe Score: ${e.unsafeScore.toFixed(1)}</div>
    </div>
  `,b.appendChild(g);const L=b.querySelector(".info-icon");L.addEventListener("mouseenter",()=>{g.style.display="block"}),L.addEventListener("mouseleave",()=>{g.style.display="none"});const h=d.getElementsByClassName("btns-div")[0];h.appendChild(f),h.appendChild(u),f.onclick=x=>{x.stopPropagation(),e.status="Ignore",l(`ignore, ${e.status}`),m(t,o)},u.onclick=x=>{l("generate"),c({command:"generateHarness",fuzzRoot:C,target:e}),e.status="HarnessGenerated",m(t,o)},d.onclick=()=>{c({command:"openLocation",filePath:e.functionLocation.filePath,offset:e.functionLocation.offset})},o.appendChild(d)}}function T(t){const o=t.nextElementSibling;t.classList.toggle("expanded")?o.style.display="block":o.style.display="none"}const R=document.querySelectorAll(".collapsible-header");R.forEach(t=>{l("Setting up collapsible header:",t.textContent),t.addEventListener("click",()=>{l("Collapsible header clicked:",t.textContent),T(t)})});F({onFuzzTargetsListed:t=>{l("🧪 Fuzz targets listed:");const o=document.getElementById("harness-list");if(o.innerHTML="",t.length===0){o.innerHTML="<div>No fuzz targets found.</div>";return}for(const n of t){const a=document.createElement("div"),r=document.createElement("button");r.textContent="Run",r.className="affirmative-button";const s=document.createElement("button");s.textContent="Delete",s.className="negative-button",s.style.marginLeft="4px",a.className="function-button",a.innerHTML=`
        <div style="font-weight:bold; margin-bottom:4px;">
          ${n.name}
        </div>
        <div>
          ${n.path.replace(C,"")}
        </div>
          <div class="btns-div" style="margin-top:6px;"></div>
      `,a.onclick=()=>{c({command:"openLocation",filePath:n.path,offset:0})};const e=a.getElementsByClassName("btns-div")[0];e.appendChild(r),e.appendChild(s),s.onclick=i=>{i.stopPropagation(),l(`Deleting fuzz target: ${n.name}`),c({command:"deleteFuzzTarget",target:n.name})},r.onclick=i=>{i.stopPropagation(),l(`Running fuzz target: ${n.name}`),c({command:"runFuzzTarget",target:n.name})},o.appendChild(a)}},onRustAnalysisDone:t=>{l("Rendering function results"),p.innerHTML="",m(t,p)},onGlobalContext:t=>{l("Global context received:",t.projectRoot);const o=t.projectRoot;o?(l("📦 Got Cargo project root: "+o),y=o,k.innerHTML=`Cargo Project Root: ${o}`):k.innerHTML="No Cargo project found.";const n=document.getElementById("fuzz-path-display"),a=t.fuzzRoot;if(a)l("🧪 Got Fuzz root: "+a),C=a,n.innerHTML=`Fuzz Harness Root: ${a}`,l("Getting Fuzz targets: "),c({command:"getFuzzTargets",fuzzRoot:a});else{n.innerText="No Fuzz root found.";const e=document.createElement("button");e.textContent="Create a Root",e.addEventListener("click",()=>{c({command:"createFuzzRoot",target:y})}),n.appendChild(e)}const r=document.createElement("div");r.id="filters-container";const s=document.createElement("div");p.appendChild(r),p.appendChild(s),t.results&&t.results.length>0&&(z=t.results,B(z,r,s),m(z,s,"priority-filter"))}});const B=(t,o,n)=>{console.log("Loading filters"),[{id:"priority-filter",label:"Priority Score",default:!0},{id:"unsafe-block-filter",label:"Unsafe Block",default:!1},{id:"parameters-filter",label:"Parameters Count",default:!1},{id:"centrality-filter",label:"Centrality Score",default:!1},{id:"usage-filter",label:"Usage Weights",default:!1}].forEach(r=>{const s=document.createElement("button");s.id=r.id,s.textContent=r.label,s.className="filter-button",s.style.marginRight="8px",r.default&&s.classList.add("selected"),s.addEventListener("click",()=>{console.log(`Filter applied: ${r.label}`),o.querySelectorAll(".filter-button").forEach(i=>i.classList.remove("selected")),s.classList.add("selected"),m(t,n,r.id)}),o.appendChild(s)})};document.getElementById("start-analyzer").addEventListener("click",()=>{c({command:"runAnalyzer",target:"none",projectPath:y})});document.getElementById("refresh-button").addEventListener("click",()=>{c({command:"showVisualization"})});
