[package]
name = "program_a-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1.4.2", features = ["derive"] } 

[dependencies.program_a]
path = ".."

[[bin]]
name = "fuzz_target_apply_operator"
path = "fuzz_targets/fuzz_target_apply_operator.rs"
test = false
doc = false
bench = false
[[bin]]
name = "bad_fuzz_target_power1"
path = "fuzz_targets/bad_fuzz_target_power1.rs"
test = false
doc = false
bench = false

[[bin]]
name = "bad_fuzz_target_power2"
path = "fuzz_targets/bad_fuzz_target_power2.rs"
test = false
doc = false
bench = false