[package]
name = "program_a-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1.4.2", features = ["derive"] } 

[dependencies.program_a]
path = ".."

[[bin]]
name = "fuzz_target_apply_operator"
path = "fuzz_targets/fuzz_target_apply_operator.rs"
test = false
doc = false
bench = false
[[bin]]
name = "fuzz_target_add"
path = "fuzz_targets/fuzz_target_add.rs"
test = false
doc = false
bench = false
[[bin]]
name = "fuzz_target_divide"
path = "fuzz_targets/fuzz_target_divide.rs"
test = false
doc = false
bench = false
[[bin]]
name = "fuzz_target_fill_and_sum"
path = "fuzz_targets/fuzz_target_fill_and_sum.rs"
test = false
doc = false
bench = false