[package]
name = "phonenumber-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[profile.release]
panic = "abort"
debug-assertions = true
overflow-checks = true
lto = "off"
codegen-units = 1

[dependencies]
libfuzzer-sys = {version = "0.15.4", package = "libafl_libfuzzer"}
arbitrary = { version = "1.4.2", features = ["derive"] } 
# libfuzzer-sys = {version = "0.4"}

# libfuzzer-sys = { git = "https://github.com/AFLplusplus/LibAFL.git", features = ["arbitrary-derive"], package = "libafl_libfuzzer" }

[dependencies.phonenumber]
path = ".."

[[bin]]
name = "fuzz_target_rfc_phonenum"
path = "fuzz_targets/fuzz_target_rfc_phonenum.rs"
test = false
doc = false
